import Link from 'next/link';
import { ArrowUpRight, Braces, Cloud, Cpu } from 'lucide-react';

const articles = [
  { tag: 'career', title: 'Construir experiência antes do primeiro estágio', text: 'O que estou aprendendo ao transformar faculdade, estudo e projetos em repertório real.' },
  { tag: 'aws', title: 'O que a cloud mudou na minha forma de pensar sistemas', text: 'Menos abstração, mais clareza sobre escolhas, custo e arquitetura.' },
  { tag: 'build', title: 'Projetos que ensinam mais que tutoriais', text: 'Como sair do código de exemplo e criar algo que resolve um problema.' },
];
const projects = [{ name: 'CampusTrack', stack: 'Python • FastAPI • AWS', text: 'Uma forma mais clara de acompanhar demandas dentro do ambiente universitário.' }];

export default function Home() {
  return <div><section className="site-container grid min-h-[620px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr] lg:py-28"><div><p className="tech-label mb-6 text-[var(--color-text-muted)]">student_dev <span className="ml-2 text-[var(--color-primary)]">{'// status: building'}</span></p><h1 className="max-w-3xl text-5xl font-bold leading-[.94] sm:text-6xl lg:text-7xl">Construindo <span className="text-[var(--color-primary)]">software</span>, carreira e conhecimento.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--color-text-muted)]">Engenharia de Software, backend, cloud, IA e projetos reais — da faculdade ao mercado.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="rounded-lg border border-[var(--color-primary)] bg-[var(--color-primary)] px-5 py-3 font-medium text-[#111] transition-transform hover:-translate-y-0.5" href="/blog">Ver artigos →</Link><Link className="rounded-lg border px-5 py-3 font-medium" href="/projetos">Projetos</Link></div></div><div className="grid-technical relative min-h-[360px] overflow-hidden border bg-[var(--color-surface)]"><div className="absolute left-[13%] top-[16%] h-20 w-20 bg-[var(--color-primary)]"/><div className="absolute right-[11%] top-[27%] h-32 w-32 border-8 border-[var(--color-text)]"/><div className="absolute bottom-[17%] left-[26%] flex h-28 w-48 items-end border border-[var(--color-border)] bg-[var(--color-graphite)] p-4"><span className="font-mono-tech text-xs text-[var(--color-primary)]">build()<br/>learning++</span></div><div className="absolute bottom-8 right-8 font-mono-tech text-xs text-[var(--color-text-muted)]">01 / system</div></div></section>
  <section className="section-rule"><div className="site-container py-20"><div className="mb-10 flex items-end justify-between"><div><p className="tech-label text-[var(--color-primary)]">01 / knowledge</p><h2 className="mt-3 text-4xl font-bold">Últimos artigos</h2></div><Link className="arrow-link hidden font-medium sm:block" href="/blog">Ver todos <span className="arrow">→</span></Link></div><div className="grid gap-4 md:grid-cols-3">{articles.map(article => <article className="group border bg-[var(--color-surface)] p-6 transition-transform hover:-translate-y-0.5" key={article.title}><div className="flex justify-between font-mono-tech text-xs"><span className="text-[var(--color-primary)]">[ {article.tag} ]</span><span className="text-[var(--color-text-muted)]">2026</span></div><h3 className="mt-10 text-2xl font-bold leading-tight">{article.title}</h3><p className="mt-4 leading-7 text-[var(--color-text-muted)]">{article.text}</p><Link className="arrow-link mt-8 inline-block font-medium" href="/blog">Ler artigo <span className="arrow">→</span></Link></article>)}</div></div></section>
  <section className="section-rule"><div className="site-container py-20"><p className="tech-label text-[var(--color-green)]">02 / build_log</p><h2 className="mt-3 text-4xl font-bold">Projetos em destaque</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{projects.map((project, i) => <article className="border bg-[var(--color-surface)] p-7" key={project.name}><div className="mb-16 flex justify-between"><span className="tech-label text-[var(--color-green)]">build_log</span>{i === 0 ? <Cloud size={20} /> : <Cpu size={20} />}</div><h3 className="text-3xl font-bold">{project.name}</h3><p className="mt-4 max-w-md leading-7 text-[var(--color-text-muted)]">{project.text}</p><p className="mt-7 font-mono-tech text-xs text-[var(--color-text-muted)]">{project.stack}</p><Link href="/projetos" className="arrow-link mt-7 inline-block font-medium">Ver projeto <span className="arrow">→</span></Link></article>)}</div></div></section>
  <section className="section-rule"><div className="site-container grid gap-10 py-20 md:grid-cols-2"><div><p className="tech-label text-[var(--color-primary)]">03 / about</p><h2 className="mt-3 text-4xl font-bold">Aprender em público. Construir com intenção.</h2></div><div><p className="text-lg leading-8 text-[var(--color-text-muted)]">Estou construindo minha carreira enquanto estudo Engenharia de Software e compartilho o que funciona no caminho.</p><Link href="/sobre" className="arrow-link mt-6 inline-block font-medium">Conheça minha trajetória <span className="arrow">→</span></Link></div></div></section>
  <section className="site-container py-20"><div className="bg-[#111] p-8 text-[#f3f0e8] sm:p-12"><Braces className="text-[var(--color-primary)]"/><p className="tech-label mt-10 text-[var(--color-primary)]">next_step</p><h2 className="mt-3 max-w-2xl text-4xl font-bold sm:text-5xl">Tecnologia sem se perder.</h2><p className="mt-5 max-w-xl text-[#bfc4c9]">Ideias, aprendizados e projetos para quem está construindo seu próprio caminho.</p><Link href="/blog" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[var(--color-primary)] px-5 py-3 font-medium text-[#111]">Começar a explorar <ArrowUpRight size={18}/></Link></div></section></div>;
}
